create table car (
	id BIGSERIAL NOT NULL PRIMARY KEY,
	make VARCHAR(100) NOT NULL,
	model VARCHAR(100) NOT NULL,
	price VARCHAR(10)
);

insert into car (id, make, model, price) values (1, 'Dodge', 'Ram Van 2500', '$5.12');
insert into car (id, make, model, price) values (2, 'Volvo', 'XC70', '$2.63');
insert into car (id, make, model, price) values (3, 'Volvo', '940', '$6.71');
insert into car (id, make, model, price) values (4, 'Chevrolet', 'Caprice', '$4.90');
insert into car (id, make, model, price) values (5, 'Jeep', 'Patriot', '$6.41');
insert into car (id, make, model, price) values (6, 'Ford', 'Crown Victoria', '$5.56');
insert into car (id, make, model, price) values (7, 'Chevrolet', 'Lumina', '$1.65');
insert into car (id, make, model, price) values (8, 'GMC', '3500 Club Coupe', '$8.75');
insert into car (id, make, model, price) values (9, 'Saab', '9000', '$2.34');
insert into car (id, make, model, price) values (10, 'Pontiac', 'Firefly', '$4.53');
insert into car (id, make, model, price) values (11, 'Chevrolet', 'S10', '$3.83');
insert into car (id, make, model, price) values (12, 'Mercury', 'Cougar', '$8.50');
insert into car (id, make, model, price) values (13, 'Mitsubishi', 'Lancer Evolution', '$5.93');
insert into car (id, make, model, price) values (14, 'Toyota', 'Corolla', '$1.71');
insert into car (id, make, model, price) values (15, 'Volvo', 'S60', '$3.08');
insert into car (id, make, model, price) values (16, 'Jaguar', 'S-Type', '$2.03');
insert into car (id, make, model, price) values (17, 'Ford', 'Mustang', '$2.07');
insert into car (id, make, model, price) values (18, 'Jeep', 'Wrangler', '$5.68');
insert into car (id, make, model, price) values (19, 'Geo', 'Storm', '$9.36');
insert into car (id, make, model, price) values (20, 'Ford', 'Focus', '$3.97');
insert into car (id, make, model, price) values (21, 'Mercedes-Benz', 'CL-Class', '$4.50');
insert into car (id, make, model, price) values (22, 'Chevrolet', 'Silverado 3500', '$9.92');
insert into car (id, make, model, price) values (23, 'Audi', 'S6', '$4.15');
insert into car (id, make, model, price) values (24, 'Pontiac', 'Grand Prix', '$4.54');
insert into car (id, make, model, price) values (25, 'Ford', 'F250', '$7.71');
insert into car (id, make, model, price) values (26, 'Infiniti', 'FX', '$4.99');
insert into car (id, make, model, price) values (27, 'Chevrolet', 'Blazer', '$6.24');
insert into car (id, make, model, price) values (28, 'Honda', 'S2000', '$8.02');
insert into car (id, make, model, price) values (29, 'Jeep', 'Commander', '$0.67');
insert into car (id, make, model, price) values (30, 'Mazda', 'B-Series', '$5.21');
insert into car (id, make, model, price) values (31, 'Mercedes-Benz', 'SLK-Class', '$7.42');
insert into car (id, make, model, price) values (32, 'Jeep', 'Compass', '$5.86');
insert into car (id, make, model, price) values (33, 'Subaru', 'Impreza WRX', '$9.07');
insert into car (id, make, model, price) values (34, 'Ford', 'Econoline E150', '$7.98');
insert into car (id, make, model, price) values (35, 'Toyota', '4Runner', '$0.25');
insert into car (id, make, model, price) values (36, 'Dodge', 'Charger', '$7.35');
insert into car (id, make, model, price) values (37, 'Ford', 'Fusion', '$8.31');
insert into car (id, make, model, price) values (38, 'Ford', 'Ranger', '$6.98');
insert into car (id, make, model, price) values (39, 'Mercedes-Benz', 'E-Class', '$5.17');
insert into car (id, make, model, price) values (40, 'Pontiac', '6000', '$8.20');
insert into car (id, make, model, price) values (41, 'Aston Martin', 'DB9', '$8.91');
insert into car (id, make, model, price) values (42, 'Chevrolet', 'Colorado', '$9.88');
insert into car (id, make, model, price) values (43, 'Dodge', 'Ram Van 1500', '$1.30');
insert into car (id, make, model, price) values (44, 'GMC', 'Envoy XUV', '$6.99');
insert into car (id, make, model, price) values (45, 'Aston Martin', 'DB9', '$8.18');
insert into car (id, make, model, price) values (46, 'Audi', 'S5', '$2.46');
insert into car (id, make, model, price) values (47, 'Hyundai', 'XG350', '$1.22');
insert into car (id, make, model, price) values (48, 'Chevrolet', 'Avalanche 1500', '$3.49');
insert into car (id, make, model, price) values (49, 'Mercedes-Benz', 'CLS-Class', '$8.66');
insert into car (id, make, model, price) values (50, 'Isuzu', 'Rodeo', '$3.20');
insert into car (id, make, model, price) values (51, 'Pontiac', 'Trans Sport', '$0.19');
insert into car (id, make, model, price) values (52, 'Chevrolet', 'G-Series 2500', '$6.51');
insert into car (id, make, model, price) values (53, 'Nissan', '200SX', '$6.06');
insert into car (id, make, model, price) values (54, 'Chevrolet', 'Camaro', '$8.23');
insert into car (id, make, model, price) values (55, 'Nissan', 'Maxima', '$9.77');
insert into car (id, make, model, price) values (56, 'Chevrolet', 'G-Series G30', '$7.25');
insert into car (id, make, model, price) values (57, 'Mazda', 'MX-6', '$1.95');
insert into car (id, make, model, price) values (58, 'GMC', 'Yukon XL 2500', '$4.14');
insert into car (id, make, model, price) values (59, 'Chrysler', 'LeBaron', '$5.34');
insert into car (id, make, model, price) values (60, 'Toyota', 'Prius', '$3.00');
insert into car (id, make, model, price) values (61, 'Subaru', 'Impreza', '$0.68');
insert into car (id, make, model, price) values (62, 'Hyundai', 'Tiburon', '$5.74');
insert into car (id, make, model, price) values (63, 'BMW', 'Z4', '$1.62');
insert into car (id, make, model, price) values (64, 'Mercedes-Benz', 'SL-Class', '$9.25');
insert into car (id, make, model, price) values (65, 'Acura', 'NSX', '$7.94');
insert into car (id, make, model, price) values (66, 'Saturn', 'Ion', '$6.29');
insert into car (id, make, model, price) values (67, 'Pontiac', 'Tempest', '$3.24');
insert into car (id, make, model, price) values (68, 'Chevrolet', 'Prizm', '$5.09');
insert into car (id, make, model, price) values (69, 'Porsche', '911', '$4.49');
insert into car (id, make, model, price) values (70, 'Mazda', 'RX-8', '$1.64');
insert into car (id, make, model, price) values (71, 'GMC', 'Safari', '$8.75');
insert into car (id, make, model, price) values (72, 'Dodge', 'D150', '$9.91');
insert into car (id, make, model, price) values (73, 'Chevrolet', 'HHR', '$5.67');
insert into car (id, make, model, price) values (74, 'Lexus', 'ES', '$1.79');
insert into car (id, make, model, price) values (75, 'GMC', '2500 Club Coupe', '$6.33');
insert into car (id, make, model, price) values (76, 'Toyota', 'Supra', '$2.69');
insert into car (id, make, model, price) values (77, 'Mercedes-Benz', 'E-Class', '$0.77');
insert into car (id, make, model, price) values (78, 'Lexus', 'GS', '$2.94');
insert into car (id, make, model, price) values (79, 'Pontiac', 'Grand Prix', '$6.20');
insert into car (id, make, model, price) values (80, 'Dodge', 'Neon', '$6.45');
insert into car (id, make, model, price) values (81, 'Cadillac', 'Escalade', '$3.91');
insert into car (id, make, model, price) values (82, 'Cadillac', 'Seville', '$1.61');
insert into car (id, make, model, price) values (83, 'Audi', 'Allroad', '$9.52');
insert into car (id, make, model, price) values (84, 'Nissan', 'Sentra', '$1.31');
insert into car (id, make, model, price) values (85, 'Infiniti', 'I', '$2.13');
insert into car (id, make, model, price) values (86, 'Ford', 'Explorer Sport', '$4.59');
insert into car (id, make, model, price) values (87, 'Ford', 'Econoline E250', '$6.69');
insert into car (id, make, model, price) values (88, 'Ford', 'E-Series', '$3.81');
insert into car (id, make, model, price) values (89, 'Subaru', 'Impreza', '$3.51');
insert into car (id, make, model, price) values (90, 'Infiniti', 'I', '$9.29');
insert into car (id, make, model, price) values (91, 'Ford', 'Tempo', '$3.26');
insert into car (id, make, model, price) values (92, 'Mitsubishi', '3000GT', '$1.42');
insert into car (id, make, model, price) values (93, 'GMC', 'Savana 1500', '$5.48');
insert into car (id, make, model, price) values (94, 'Buick', 'Riviera', '$3.48');
insert into car (id, make, model, price) values (95, 'Ford', 'F150', '$2.83');
insert into car (id, make, model, price) values (96, 'Chrysler', 'Sebring', '$6.65');
insert into car (id, make, model, price) values (97, 'Mazda', 'CX-7', '$1.15');
insert into car (id, make, model, price) values (98, 'BMW', '7 Series', '$2.37');
insert into car (id, make, model, price) values (99, 'Dodge', 'Ram 50', '$8.12');
insert into car (id, make, model, price) values (100, 'Chevrolet', 'Silverado', '$8.65');
